// @flow

export const TOO_MACH_MEMBERS = 'TOO_MACH_MEMBERS';
export const TOO_FEW_MEMBERS = 'TOO_FEW_MEMBERS';
export const GAME_NOT_FOUND = 'GAME_NOT_FOUND';
export const GAME_PLAYER_ALREADY_EXIST = 'GAME_PLAYER_ALREADY_EXIST';
export const GAME_CURRENT_ROUND_NOT_FINISHED = 'GAME_CURRENT_ROUND_NOT_FINISHED';
export const GAME_IS_FINISHED = 'GAME_IS_FINISHED';

export const PLAYER_NOT_FOUND = 'PLAYER_NOT_FOUND';
export const WRONG_PLAYER_ORDER = 'WRONG_PLAYER_ORDER';
export const WRONG_PLAYERS_COUNT = 'WRONG_PLAYERS_COUNT';
export const ROUND_ALREADY_STARTED = 'ROUND_ALREADY_STARTED';
export const ROUND_WRONG_PREDICTION_COUNT = 'ROUND_WRONG_PREDICTION_COUNT';
export const ROUND_WRONG_PLAYER_CARDS_COUNT = 'ROUND_WRONG_PLAYER_CARDS_COUNT';
export const ROUND_STEP_WRONG_STATUS = 'ROUND_STEP_WRONG_STATUS';
export const ROUND_STEP_CARD_NOT_EXIST = 'ROUND_STEP_CARD_NOT_EXIST';
export const PLAYER_ALREADY_PLACED_A_BET = 'PLAYER_ALREADY_PLACED_A_BET';
export const ROUND_STEP_CARD_INCORRECT = 'ROUND_STEP_CARD_INCORRECT';

export const ERROR_PLAYER_CARD_EXIST = 'ERROR_PLAYER_CARD_EXIST';
export const ERROR_PLAYER_CARD_NOT_EXIST = 'ERROR_PLAYER_CARD_NOT_EXIST';
