// @flow

export const TOO_MACH_MEMBERS = 'TOO_MACH_MEMBERS';
export const GAME_NOT_FOUND = 'GAME_NOT_FOUND';

export const PLAYER_NOT_FOUND = 'PLAYER_NOT_FOUND';
export const WRONG_PLAYER_ORDER = 'WRONG_PLAYER_ORDER';
export const ROUND_STEP_CARD_INCORRECT = 'ROUND_STEP_CARD_INCORRECT';
